package de.enough.polish.netbeans;

import javax.swing.JFileChooser;
import javax.swing.JPanel;

public final class PolishProjectSetupVisualPanel1 extends JPanel {
    
    /** Creates new form PolishProjectSetupVisualPanel1 */
    public PolishProjectSetupVisualPanel1() {
        initComponents();
    }
    
    public String getName() {
        return "Installation Settings";
    }
    
    private void openFileChooser() {
        JFileChooser chooser = new JFileChooser();
        chooser.setVisible( true );
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        polishHomeField = new javax.swing.JTextField();
        openFileChooserButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("J2ME Polish Installation folder:");
        add(jLabel1, java.awt.BorderLayout.WEST);

        add(polishHomeField, java.awt.BorderLayout.CENTER);

        openFileChooserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChooseInstallFolderButtonHandler(evt);
            }
        });

        add(openFileChooserButton, java.awt.BorderLayout.EAST);

    }// </editor-fold>//GEN-END:initComponents

    private void ChooseInstallFolderButtonHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseInstallFolderButtonHandler
// TODO add your handling code here:
        openFileChooser();
    }//GEN-LAST:event_ChooseInstallFolderButtonHandler
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton openFileChooserButton;
    private javax.swing.JTextField polishHomeField;
    // End of variables declaration//GEN-END:variables
    
}

