package de.enough.polish.netbeans;

import javax.swing.JPanel;

public final class PolishProjectSetupVisualPanel4 extends JPanel {
    
    /** Creates new form PolishProjectSetupVisualPanel4 */
    public PolishProjectSetupVisualPanel4() {
        initComponents();
    }
    
    public String getName() {
        return "Step #4";
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}

