// generated by de.enough.doc2java.Doc2Java (www.enough.de) on Sun Feb 29 19:10:56 CET 2004
package javax.microedition.rms;

/**
 * Thrown to indicate an operation could not be completed because the
 * record ID was invalid.
 * <HR>
 * 
 * 
 * @since MIDP 1.0
 */
public class InvalidRecordIDException extends RecordStoreException
{
	/**
	 * Constructs a new <code>InvalidRecordIDException</code> with the
	 * specified detail message.
	 * 
	 * @param message - the detail message
	 */
	public InvalidRecordIDException( String message)
	{
		//TODO implement InvalidRecordIDException
	}

	/**
	 * Constructs a new <code>InvalidRecordIDException</code> with no detail
	 * message.</DL>
	 * 
	 * 
	 */
	public InvalidRecordIDException()
	{
		//TODO implement InvalidRecordIDException
	}

}
