// generated by de.enough.doc2java.Doc2Java (www.enough.de) on Tue Mar 25 12:43:45 CET 2008
package de.enough.polish.drone.rms;

/**
 * Thrown to indicate that an operation was attempted on a closed record store.
 * 
 * Thrown to indicate that an operation was attempted on a closed record store.
 * 
 * <DD>MIDP 1.0</DD>
 * <HR>
 * 
 * <!-- ======== NESTED CLASS SUMMARY ======== -->
 * 
 * 
 * <!-- =========== FIELD SUMMARY =========== -->
 * 
 * 
 * <!-- ======== CONSTRUCTOR SUMMARY ======== -->
 * 
 * <A NAME="constructor_summary"><!-- --></A>
 * <TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
 * <TD COLSPAN=2><FONT SIZE="+2">
 * <B>Constructor Summary</B></FONT></TD>
 * </TR>
 * <TR BGCOLOR="white" CLASS="TableRowColor">
 * <TD><CODE><B><A HREF="RecordStoreNotOpenException.html#RecordStoreNotOpenException()" tppabs="http://java.sun.com/javame/reference/apis/jsr118/javax/microedition/rms/RecordStoreNotOpenException.html#RecordStoreNotOpenException()">RecordStoreNotOpenException</A></B>()</CODE>
 * 
 * <BR>
 * &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Constructs a new <code>RecordStoreNotOpenException</code> with no detail
 * message.</TD>
 * </TR>
 * <TR BGCOLOR="white" CLASS="TableRowColor">
 * <TD><CODE><B><A HREF="RecordStoreNotOpenException.html#RecordStoreNotOpenException(java.lang.String)" tppabs="http://java.sun.com/javame/reference/apis/jsr118/javax/microedition/rms/RecordStoreNotOpenException.html#RecordStoreNotOpenException(java.lang.String)">RecordStoreNotOpenException</A></B>(<A HREF="../../../java/lang/String.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/String.html" title="class in java.lang">String</A>&nbsp;message)</CODE>
 * 
 * <BR>
 * &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Constructs a new <code>RecordStoreNotOpenException</code> with the
 * specified detail message.</TD>
 * </TR>
 * </TABLE>
 * &nbsp;
 * <!-- ========== METHOD SUMMARY =========== -->
 * 
 * <A NAME="methods_inherited_from_class_java.lang.Throwable"><!-- --></A>
 * <TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
 * <TR BGCOLOR="#EEEEFF" CLASS="TableSubHeadingColor">
 * <TD><B>Methods inherited from class java.lang.<A HREF="../../../java/lang/Throwable.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/Throwable.html" title="class in java.lang">Throwable</A></B></TD>
 * </TR>
 * <TR BGCOLOR="white" CLASS="TableRowColor">
 * <TD><CODE><A HREF="../../../java/lang/Throwable.html#getMessage()" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/Throwable.html#getMessage()">getMessage</A>, <A HREF="../../../java/lang/Throwable.html#printStackTrace()" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/Throwable.html#printStackTrace()">printStackTrace</A>, <A HREF="../../../java/lang/Throwable.html#toString()" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/Throwable.html#toString()">toString</A></CODE></TD>
 * </TR>
 * </TABLE>
 * &nbsp;<A NAME="methods_inherited_from_class_java.lang.Object"><!-- --></A>
 * <TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
 * <TR BGCOLOR="#EEEEFF" CLASS="TableSubHeadingColor">
 * <TD><B>Methods inherited from class java.lang.<A HREF="../../../java/lang/Object.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/Object.html" title="class in java.lang">Object</A></B></TD>
 * </TR>
 * <TR BGCOLOR="white" CLASS="TableRowColor">
 * <TD><CODE><A HREF="../../../java/lang/Object.html#equals(java.lang.Object)" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/Object.html#equals(java.lang.Object)">equals</A>, <A HREF="../../../java/lang/Object.html#getClass()" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/Object.html#getClass()">getClass</A>, <A HREF="../../../java/lang/Object.html#hashCode()" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/Object.html#hashCode()">hashCode</A>, <A HREF="../../../java/lang/Object.html#notify()" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/Object.html#notify()">notify</A>, <A HREF="../../../java/lang/Object.html#notifyAll()" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/Object.html#notifyAll()">notifyAll</A>, <A HREF="../../../java/lang/Object.html#wait()" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/Object.html#wait()">wait</A>, <A HREF="../../../java/lang/Object.html#wait(long)" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/Object.html#wait(long)">wait</A>, <A HREF="../../../java/lang/Object.html#wait(long, int)" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/Object.html#wait(long, int)">wait</A></CODE></TD>
 * </TR>
 * </TABLE>
 * &nbsp;
 * 
 * <!-- ============ FIELD DETAIL =========== -->
 * 
 * 
 * <!-- ========= CONSTRUCTOR DETAIL ======== -->
 * 
 * <A NAME="constructor_detail"><!-- --></A>
 * <TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
 * <TD COLSPAN=1><FONT SIZE="+2">
 * <B>Constructor Detail</B></FONT></TD>
 * </TR>
 * </TABLE>
 * 
 * <A NAME="RecordStoreNotOpenException(java.lang.String)"><!-- --></A><H3>
 * RecordStoreNotOpenException</H3>
 * <PRE>
 * public <B>RecordStoreNotOpenException</B>(<A HREF="../../../java/lang/String.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/java/lang/String.html" title="class in java.lang">String</A>&nbsp;message)</PRE>
 * <DD>Constructs a new <code>RecordStoreNotOpenException</code> with the
 * specified detail message.
 * <HR>
 * 
 * <A NAME="RecordStoreNotOpenException()"><!-- --></A><H3>
 * RecordStoreNotOpenException</H3>
 * <PRE>
 * public <B>RecordStoreNotOpenException</B>()</PRE>
 * <DD>Constructs a new <code>RecordStoreNotOpenException</code> with no detail
 * message.
 * 
 * <!-- ============ METHOD DETAIL ========== -->
 * 
 * <!-- ========= END OF CLASS DATA ========= -->
 * <HR>
 * 
 * 
 * <!-- ======= START OF BOTTOM NAVBAR ====== -->
 * <A NAME="navbar_bottom"><!-- --></A>
 * <A HREF="#skip-navbar_bottom" title="Skip navigation links"></A>
 * <TABLE BORDER="0" WIDTH="100%" CELLPADDING="1" CELLSPACING="0" SUMMARY="">
 * <TR>
 * <TD COLSPAN=3 BGCOLOR="#EEEEFF" CLASS="NavBarCell1">
 * <A NAME="navbar_bottom_firstrow"><!-- --></A>
 * <TABLE BORDER="0" CELLPADDING="0" CELLSPACING="3" SUMMARY="">
 * <TR ALIGN="center" VALIGN="top">
 * <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../overview-summary.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/overview-summary.html"><FONT CLASS="NavBarFont1"><B>Overview</B></FONT></A>&nbsp;</TD>
 * <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="package-summary.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/javax/microedition/rms/package-summary.html"><FONT CLASS="NavBarFont1"><B>Package</B></FONT></A>&nbsp;</TD>
 * <TD BGCOLOR="#FFFFFF" CLASS="NavBarCell1Rev"> &nbsp;<FONT CLASS="NavBarFont1Rev"><B>Class</B></FONT>&nbsp;</TD>
 * <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="class-use/RecordStoreNotOpenException.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/javax/microedition/rms/class-use/RecordStoreNotOpenException.html"><FONT CLASS="NavBarFont1"><B>Use</B></FONT></A>&nbsp;</TD>
 * <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="package-tree.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/javax/microedition/rms/package-tree.html"><FONT CLASS="NavBarFont1"><B>Tree</B></FONT></A>&nbsp;</TD>
 * <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../deprecated-list.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/deprecated-list.html"><FONT CLASS="NavBarFont1"><B>Deprecated</B></FONT></A>&nbsp;</TD>
 * <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../index-all.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/index-all.html"><FONT CLASS="NavBarFont1"><B>Index</B></FONT></A>&nbsp;</TD>
 * <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../help-doc.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/help-doc.html"><FONT CLASS="NavBarFont1"><B>Help</B></FONT></A>&nbsp;</TD>
 * </TR>
 * </TABLE>
 * </TD>
 * <TD ALIGN="right" VALIGN="top" ROWSPAN=3><EM>
 * <strong>MID Profile</strong></EM>
 * </TD>
 * </TR>
 * 
 * <TR>
 * <TD BGCOLOR="white" CLASS="NavBarCell2"><FONT SIZE="-2">
 * &nbsp;<A HREF="RecordStoreNotFoundException.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/javax/microedition/rms/RecordStoreNotFoundException.html" title="class in javax.microedition.rms"><B>PREV CLASS</B></A>&nbsp;
 * &nbsp;NEXT CLASS</FONT></TD>
 * <TD BGCOLOR="white" CLASS="NavBarCell2"><FONT SIZE="-2">
 * <A HREF="../../../index.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/index.html" target="_top"><B>FRAMES</B></A>  &nbsp;
 * &nbsp;<A HREF="RecordStoreNotOpenException.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/javax/microedition/rms/RecordStoreNotOpenException.html" target="_top"><B>NO FRAMES</B></A>  &nbsp;
 * &nbsp;<SCRIPT type="text/javascript">
 * <!--
 * if(window==top) {
 * document.writeln('<A HREF="../../../allclasses-noframe.html"/*tpa=http://java.sun.com/javame/reference/apis/jsr118/allclasses-noframe.html><B>All Classes</B></A>');
 * }
 * //-->
 * </SCRIPT>
 * <NOSCRIPT>
 * <A HREF="../../../allclasses-noframe.html" tppabs="http://java.sun.com/javame/reference/apis/jsr118/allclasses-noframe.html"><B>All Classes</B></A>
 * </NOSCRIPT>
 * 
 * </FONT></TD>
 * </TR>
 * <TR>
 * <TD VALIGN="top" CLASS="NavBarCell3"><FONT SIZE="-2">
 * SUMMARY:&nbsp;NESTED&nbsp;|&nbsp;FIELD&nbsp;|&nbsp;<A HREF="#constructor_summary">CONSTR</A>&nbsp;|&nbsp;<A HREF="#methods_inherited_from_class_java.lang.Throwable">METHOD</A></FONT></TD>
 * <TD VALIGN="top" CLASS="NavBarCell3"><FONT SIZE="-2">
 * DETAIL:&nbsp;FIELD&nbsp;|&nbsp;<A HREF="#constructor_detail">CONSTR</A>&nbsp;|&nbsp;METHOD</FONT></TD>
 * </TR>
 * </TABLE>
 * <A NAME="skip-navbar_bottom"></A>
 * <!-- ======== END OF BOTTOM NAVBAR ======= -->
 * 
 * <HR>
 * <small>Copyright &copy; 2006 Sun Microsystems, Inc. and Motorola, Inc. All rights reserved. <b>Use is subject to <a href="http://java.sun.com/javame/reference/apis/license.html" target="_top">License Terms</a>.</b> Your use of this web site or any of its content or software indicates your agreement to be bound by these License Terms.<br><br>For more information, please consult the <a href="http://jcp.org/en/jsr/detail?id=118" target="_top">JSR 118 specification.</a></small>
 * </BODY>
 * <script language="JavaScript" src="../../../../../../../js/omi/jsc/s_code_remote.js" tppabs="http://java.sun.com/js/omi/jsc/s_code_remote.js"></script></HTML>
 * 
 * @since 
 */
public class RecordStoreNotOpenException extends RecordStoreException
{
	/**
	 * Constructs a new <code>RecordStoreNotOpenException</code> with the
	 * specified detail message.
	 * <P>
	 * 
	 * @param message - the detail message
	 */
	public RecordStoreNotOpenException( String message)
	{
		//TODO implement RecordStoreNotOpenException
	}

	/**
	 * Constructs a new <code>RecordStoreNotOpenException</code> with no detail
	 * message.
	 * <P>
	 * 
	 * 
	 */
	public RecordStoreNotOpenException()
	{
		//TODO implement RecordStoreNotOpenException
	}

}
